---
- include: undercloud-config.yml
  when: tempest_undercloud
  tags:
    - tempest-undercloud-config

- include: pre-tempest.yml
  when: tempest_config
  tags:
    - pre-tempest-config

- include: run-tempest.yml
  when: run_tempest
  tags:
    - run-tempest

- include: post-tempest.yml
  when: post_tempest
  tags:
    - post-tempest